version: "3.8"

services:
  app:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    command: yarn test:integration
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
